

name: Tests Saucedemo

on:
  push:
    branches: [main]
    paths:
      - 'tests/02-Automatizados/Pruebas-saucedemo/**'
  pull_request:
    branches: [main]
    paths:
      - 'tests/02-Automatizados/Pruebas-saucedemo/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/02-Automatizados/Pruebas-saucedemo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps chromium
      - run: pytest -v